from pathlib import Path
import re

root = Path(r'C:\Users\hp\OneDrive\Desktop\quizpathshala_website')


def read(rel):
    return (root / rel).read_text(encoding='utf-8')


def write(rel, content):
    (root / rel).write_text(content, encoding='utf-8')


def replace_once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f'missing pattern for {label}')
    return text.replace(old, new, 1)

# db/database.py
text = read('db/database.py')
text = re.sub(
    r'"questions": "question_id",.*?"notifications": "notification_id",',
    '"questions": "question_id",\n        "question_reports": "report_id",\n        "notifications": "notification_id",',
    text,
    count=1,
    flags=re.S,
)
text = replace_once(
    text,
    '            conn.execute(\n                "CREATE INDEX IF NOT EXISTS idx_support_messages_created_at ON support_messages(created_at DESC)"\n            )\n        self._initialized = True',
    '            conn.execute(\n                "CREATE INDEX IF NOT EXISTS idx_support_messages_created_at ON support_messages(created_at DESC)"\n            )\n            conn.execute(\n                "CREATE INDEX IF NOT EXISTS idx_question_reports_created_at ON question_reports(created_at DESC)"\n            )\n            conn.execute(\n                "CREATE INDEX IF NOT EXISTS idx_question_reports_user_question ON question_reports(user_id, question_id, created_at DESC)"\n            )\n        self._initialized = True',
    'db indexes',
)
text = replace_once(
    text,
    '            """\n            CREATE TABLE IF NOT EXISTS support_messages (\n                support_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,',
    '            """\n            CREATE TABLE IF NOT EXISTS question_reports (\n                report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n                user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,\n                question_id INTEGER NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,\n                set_id INTEGER NOT NULL REFERENCES exam_sets(set_id) ON DELETE CASCADE,\n                reason TEXT NOT NULL,\n                created_at TEXT NOT NULL\n            )\n            """,\n            """\n            CREATE TABLE IF NOT EXISTS support_messages (\n                support_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,',
    'postgres question_reports',
)
text = replace_once(
    text,
    '        CREATE TABLE IF NOT EXISTS support_messages (\n            support_id INTEGER PRIMARY KEY AUTOINCREMENT,',
    '        CREATE TABLE IF NOT EXISTS question_reports (\n            report_id INTEGER PRIMARY KEY AUTOINCREMENT,\n            user_id INTEGER NOT NULL,\n            question_id INTEGER NOT NULL,\n            set_id INTEGER NOT NULL,\n            reason TEXT NOT NULL,\n            created_at TEXT NOT NULL,\n            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,\n            FOREIGN KEY (question_id) REFERENCES questions(question_id) ON DELETE CASCADE,\n            FOREIGN KEY (set_id) REFERENCES exam_sets(set_id) ON DELETE CASCADE\n        );\n\n        CREATE TABLE IF NOT EXISTS support_messages (\n            support_id INTEGER PRIMARY KEY AUTOINCREMENT,',
    'sqlite question_reports',
)
write('db/database.py', text)

# services/web_identity_service.py
text = read('services/web_identity_service.py')
text = replace_once(text, '        "phone_number",\n        "user_role",', '        "phone_number",\n        "timezone",\n        "user_role",', 'identity fields')
text = replace_once(text, '            "phone_number": user.get("phone_number"),\n            "user_role": str(user.get("user_role") or ("admin" if user.get("is_admin") else "user")),', '            "phone_number": user.get("phone_number"),\n            "timezone": user.get("timezone"),\n            "user_role": str(user.get("user_role") or ("admin" if user.get("is_admin") else "user")),', 'identity snapshot')
write('services/web_identity_service.py', text)

# webhook_server.py
text = read('webhook_server.py')
text = replace_once(text, 'from utils.logging_utils import get_logger, setup_logging\n', 'from utils.logging_utils import get_logger, setup_logging\nfrom utils.timezone_utils import format_user_datetime\n', 'webhook import')
text = replace_once(text, '    app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 86400\n    app.json.ensure_ascii = False\n', '    app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 86400\n    app.json.ensure_ascii = False\n    app.jinja_env.filters["format_user_datetime"] = format_user_datetime\n', 'jinja filter')
write('webhook_server.py', text)

# services/web_quiz_service.py
text = read('services/web_quiz_service.py')
insert_after = '        return attempts\n\n'
method_block = '''        return attempts\n\n    def submit_question_report(self, *, user_id: int, question_id: int, set_id: int, reason: str) -> int:\n        cleaned_reason = " ".join(str(reason or "").strip().split())\n        if len(cleaned_reason) < 5:\n            raise ValueError("Please add a short reason with at least 5 characters.")\n\n        with database.connection() as conn:\n            question_row = conn.execute(\n                "SELECT question_id, set_id FROM questions WHERE question_id = ?",\n                (question_id,),\n            ).fetchone()\n            if not question_row:\n                raise ValueError("This question could not be found anymore.")\n            if int(question_row["set_id"]) != int(set_id):\n                raise ValueError("Question report could not be matched to this quiz set.")\n\n            cursor = conn.execute(\n                """\n                INSERT INTO question_reports (user_id, question_id, set_id, reason, created_at)\n                VALUES (?, ?, ?, ?, ?)\n                """,\n                (user_id, question_id, set_id, cleaned_reason, self._timestamp_now()),\n            )\n\n        report_id = int(cursor.lastrowid)\n        self.logger.info(\n            "Question reported | report_id=%s user_id=%s question_id=%s set_id=%s",\n            report_id,\n            user_id,\n            question_id,\n            set_id,\n        )\n        return report_id\n\n'''
text = replace_once(text, insert_after, method_block, 'quiz report method')
write('services/web_quiz_service.py', text)

# services/web_admin_service.py
text = read('services/web_admin_service.py')
text = replace_once(
    text,
    '            support_tickets = [dict(row) for row in conn.execute(\n                """\n                SELECT * FROM support_messages\n                ORDER BY created_at DESC\n                LIMIT ?\n                """,\n                (50,),\n            ).fetchall()]\n',
    '            support_tickets = [dict(row) for row in conn.execute(\n                """\n                SELECT * FROM support_messages\n                ORDER BY created_at DESC\n                LIMIT ?\n                """,\n                (50,),\n            ).fetchall()]\n            question_reports = [dict(row) for row in conn.execute(\n                """\n                SELECT\n                    qr.*,\n                    u.full_name,\n                    q.question_text,\n                    s.title AS set_title,\n                    e.title AS exam_title\n                FROM question_reports qr\n                LEFT JOIN users u ON u.user_id = qr.user_id\n                LEFT JOIN questions q ON q.question_id = qr.question_id\n                LEFT JOIN exam_sets s ON s.set_id = qr.set_id\n                LEFT JOIN exams e ON e.exam_id = s.exam_id\n                ORDER BY qr.created_at DESC, qr.report_id DESC\n                LIMIT ?\n                """,\n                (50,),\n            ).fetchall()]\n',
    'admin reports query',
)
text = replace_once(text, '            "support_tickets": support_tickets,\n            "admins": admins,', '            "support_tickets": support_tickets,\n            "question_reports": question_reports,\n            "admins": admins,', 'admin payload')
write('services/web_admin_service.py', text)

# routes/quiz.py
text = read('routes/quiz.py')
text = replace_once(text, '@quiz_blueprint.route("/result")\n@login_required\ndef result():\n', '@quiz_blueprint.route("/result", methods=["GET", "POST"])\n@login_required\ndef result():\n', 'quiz result methods')
text = replace_once(text, '    if not user_id:\n        flash("Please log in to continue.", "error")\n        return redirect(url_for("auth.login"))\n\n    summary = web_quiz_service.load_completed_summary(user_id) or session.get("last_quiz_result")\n', '    if not user_id:\n        flash("Please log in to continue.", "error")\n        return redirect(url_for("auth.login"))\n\n    if request.method == "POST":\n        action = (request.form.get("action") or "").strip()\n        if action == "report_question":\n            try:\n                web_quiz_service.submit_question_report(\n                    user_id=user_id,\n                    question_id=int(request.form.get("question_id", "0")),\n                    set_id=int(request.form.get("set_id", "0")),\n                    reason=request.form.get("reason", ""),\n                )\n                flash("Your report has been submitted to the admin team.", "success")\n            except Exception as exc:\n                flash(str(exc), "error")\n        return redirect(url_for("quiz.result"))\n\n    summary = web_quiz_service.load_completed_summary(user_id) or session.get("last_quiz_result")\n', 'quiz result post')
text = replace_once(text, '        "play.html",\n        page_title="Play Quiz",\n        user=user,\n', '        "play.html",\n        page_title="Play Quiz",\n        body_class="quiz-play-page",\n        compact_quiz_nav=True,\n        user=user,\n', 'play template args')
text = replace_once(text, '        "result.html",\n        page_title="Quiz Result",\n        user=user,\n', '        "result.html",\n        page_title="Quiz Result",\n        body_class="quiz-result-page",\n        user=user,\n', 'result template args')
write('routes/quiz.py', text)

# routes/admin.py
text = read('routes/admin.py')
text = replace_once(text, 'from utils.logging_utils import get_logger\n', 'from utils.logging_utils import get_logger\nfrom utils.question_image_upload import delete_question_image, save_question_image\n', 'admin imports')
old_block = '''            elif action == "save_question":
                question_id = int(request.form.get("question_id", "0") or "0") or None
                question_result = (
                    web_admin_service.update_question(
                        question_id=question_id,
                        set_id=int(request.form.get("set_id", "0")),
                        question_text=request.form.get("question_text", ""),
                        options=[
                            request.form.get("option_a", ""),
                            request.form.get("option_b", ""),
                            request.form.get("option_c", ""),
                            request.form.get("option_d", ""),
                        ],
                        correct_option=request.form.get("correct_option", ""),
                        explanation=request.form.get("explanation") or None,
                        image_path=request.form.get("image_path") or None,
                        time_limit=int(request.form.get("time_limit", "0") or "0") or None,
                    )
                    if question_id
                    else web_admin_service.add_question(
                        set_id=int(request.form.get("set_id", "0")),
                        question_text=request.form.get("question_text", ""),
                        options=[
                            request.form.get("option_a", ""),
                            request.form.get("option_b", ""),
                            request.form.get("option_c", ""),
                            request.form.get("option_d", ""),
                        ],
                        correct_option=request.form.get("correct_option", ""),
                        explanation=request.form.get("explanation") or None,
                        image_path=request.form.get("image_path") or None,
                        time_limit=int(request.form.get("time_limit", "0") or "0") or None,
                    )
                )
                operation = question_result.get("operation") or "saved"
'''
new_block = '''            elif action == "save_question":
                question_id = int(request.form.get("question_id", "0") or "0") or None
                existing_question = web_admin_service.get_question(question_id) if question_id else None
                existing_image_path = (
                    request.form.get("current_image_path")
                    or (existing_question.get("image_path") if existing_question else None)
                    or None
                )
                remove_current_image = bool(request.form.get("remove_image"))
                uploaded_image_path = None
                try:
                    uploaded_image_path = save_question_image(request.files.get("question_image"))
                    resolved_image_path = uploaded_image_path or (None if remove_current_image else existing_image_path)
                    question_result = (
                        web_admin_service.update_question(
                            question_id=question_id,
                            set_id=int(request.form.get("set_id", "0")),
                            question_text=request.form.get("question_text", ""),
                            options=[
                                request.form.get("option_a", ""),
                                request.form.get("option_b", ""),
                                request.form.get("option_c", ""),
                                request.form.get("option_d", ""),
                            ],
                            correct_option=request.form.get("correct_option", ""),
                            explanation=request.form.get("explanation") or None,
                            image_path=resolved_image_path,
                            time_limit=int(request.form.get("time_limit", "0") or "0") or None,
                        )
                        if question_id
                        else web_admin_service.add_question(
                            set_id=int(request.form.get("set_id", "0")),
                            question_text=request.form.get("question_text", ""),
                            options=[
                                request.form.get("option_a", ""),
                                request.form.get("option_b", ""),
                                request.form.get("option_c", ""),
                                request.form.get("option_d", ""),
                            ],
                            correct_option=request.form.get("correct_option", ""),
                            explanation=request.form.get("explanation") or None,
                            image_path=resolved_image_path,
                            time_limit=int(request.form.get("time_limit", "0") or "0") or None,
                        )
                    )
                except Exception:
                    if uploaded_image_path:
                        delete_question_image(uploaded_image_path)
                    raise
                if existing_image_path and existing_image_path != resolved_image_path:
                    delete_question_image(existing_image_path)
                operation = question_result.get("operation") or "saved"
'''
text = replace_once(text, old_block, new_block, 'admin save question block')
write('routes/admin.py', text)

# templates/base.html
text = read('templates/base.html')
text = replace_once(text, '<body>\n    <header class="site-header" data-collapsible-navbar>', '<body class="{{ body_class or \'\' }}">\n    <header class="site-header{% if compact_quiz_nav %} navbar-collapsed navbar-locked{% endif %}" data-collapsible-navbar data-navbar-locked="{{ \'true\' if compact_quiz_nav else \'false\' }}">', 'base body/header')
write('templates/base.html', text)

# templates/result.html
text = read('templates/result.html')
text = replace_once(text, '<p><strong>Started at:</strong> {{ summary.started_at or \'-\' }}</p>\n            <p><strong>Completed at:</strong> {{ summary.completed_at or \'-\' }}</p>', '<p><strong>Started at:</strong> {{ summary.started_at|format_user_datetime(user) }}</p>\n            <p><strong>Completed at:</strong> {{ summary.completed_at|format_user_datetime(user) }}</p>', 'result timestamps')
text = replace_once(text, '<td>{{ attempt.created_at }}</td>', '<td>{{ attempt.created_at|format_user_datetime(user) }}</td>', 'result attempts timestamp')
text = replace_once(text, '                {% if item.explanation %}\n                <p><strong>Explanation:</strong> {{ item.explanation }}</p>\n                {% endif %}\n            </article>', '                {% if item.explanation %}\n                <p><strong>Explanation:</strong> {{ item.explanation }}</p>\n                {% endif %}\n                <details class="report-question-box">\n                    <summary>Report wrong question</summary>\n                    <form method="post" accept-charset="UTF-8" data-disable-on-submit="true">\n                        <input type="hidden" name="action" value="report_question">\n                        <input type="hidden" name="question_id" value="{{ item.question_id }}">\n                        <input type="hidden" name="set_id" value="{{ summary.set_id }}">\n                        <label for="report_reason_{{ item.question_id }}">Reason / comment</label>\n                        <textarea id="report_reason_{{ item.question_id }}" name="reason" rows="3" placeholder="Tell us what is wrong in this question, option, answer, image, or explanation."></textarea>\n                        <button class="button button-secondary button-small" type="submit">Submit Report</button>\n                    </form>\n                </details>\n            </article>', 'result report box')
write('templates/result.html', text)

# templates/dashboard.html
text = read('templates/dashboard.html')
text = replace_once(text, '<td>{{ attempt.created_at }}</td>', '<td>{{ attempt.created_at|format_user_datetime(user) }}</td>', 'dashboard timestamp')
write('templates/dashboard.html', text)

# templates/admin_dashboard.html
text = read('templates/admin_dashboard.html')
text = replace_once(text, '<form method="post" accept-charset="UTF-8" data-disable-on-submit="true" data-admin-preserve="true">\n                <input type="hidden" name="action" value="save_question">', '<form method="post" accept-charset="UTF-8" enctype="multipart/form-data" data-disable-on-submit="true" data-admin-preserve="true">\n                <input type="hidden" name="action" value="save_question">', 'admin form enctype')
text = replace_once(text, '<input type="hidden" name="question_id" value="{{ editing_question.question_id if editing_question else \'\' }}">', '<input type="hidden" name="question_id" value="{{ editing_question.question_id if editing_question else \'\' }}">\n                <input type="hidden" name="current_image_path" value="{{ editing_question.image_path if editing_question and editing_question.image_path else \'\' }}">', 'admin current image hidden')
text = replace_once(text, '<label for="image_path">Image path (optional)</label>\n                <input id="image_path" name="image_path" type="text" placeholder="data/images/example.jpg" value="{{ editing_question.image_path if editing_question and editing_question.image_path else \'\' }}">', '<label for="question_image">Question image (optional)</label>\n                <input id="question_image" name="question_image" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp">\n                {% if editing_question and editing_question.image_path %}\n                <img class="question-image admin-question-image-preview" src="{{ url_for(\'media_file\', relative_path=editing_question.image_path) }}" alt="Current question image">\n                <label><input type="checkbox" name="remove_image" value="1"> Remove current image</label>\n                {% endif %}', 'admin image chooser')
text = replace_once(text, '        <div class="data-card" id="support-panel" data-admin-panel tabindex="-1">\n            <h2>Support Tickets</h2>\n            <table>\n                <thead>\n                    <tr><th>ID</th><th>User</th><th>Status</th><th>Message</th></tr>\n                </thead>\n                <tbody>\n                    {% for ticket in support_tickets %}\n                    <tr>\n                        <td>{{ ticket.support_id }}</td>\n                        <td>{{ ticket.full_name }}</td>\n                        <td>{{ ticket.status }}</td>\n                        <td>{{ ticket.message }}</td>\n                    </tr>\n                    {% else %}\n                    <tr><td colspan="4">No support tickets yet.</td></tr>\n                    {% endfor %}\n                </tbody>\n            </table>\n        </div>\n    </div>\n</section>', '        <div class="data-card" id="support-panel" data-admin-panel tabindex="-1">\n            <h2>Support Tickets</h2>\n            <table>\n                <thead>\n                    <tr><th>ID</th><th>User</th><th>Status</th><th>Message</th></tr>\n                </thead>\n                <tbody>\n                    {% for ticket in support_tickets %}\n                    <tr>\n                        <td>{{ ticket.support_id }}</td>\n                        <td>{{ ticket.full_name }}</td>\n                        <td>{{ ticket.status }}</td>\n                        <td>{{ ticket.message }}</td>\n                    </tr>\n                    {% else %}\n                    <tr><td colspan="4">No support tickets yet.</td></tr>\n                    {% endfor %}\n                </tbody>\n            </table>\n        </div>\n\n        <div class="data-card" id="question-reports-panel" data-admin-panel tabindex="-1">\n            <h2>Question Reports</h2>\n            <table>\n                <thead>\n                    <tr><th>When</th><th>User</th><th>Exam</th><th>Set</th><th>Question</th><th>Reason</th></tr>\n                </thead>\n                <tbody>\n                    {% for report in question_reports %}\n                    <tr>\n                        <td>{{ report.created_at|format_user_datetime(current_user) }}</td>\n                        <td>{{ report.full_name or report.user_id }}</td>\n                        <td>{{ report.exam_title or \'-\' }}</td>\n                        <td>{{ report.set_title or \'-\' }}</td>\n                        <td>{{ report.question_text or (\'Question #\' ~ report.question_id) }}</td>\n                        <td>{{ report.reason }}</td>\n                    </tr>\n                    {% else %}\n                    <tr><td colspan="6">No question reports yet.</td></tr>\n                    {% endfor %}\n                </tbody>\n            </table>\n        </div>\n    </div>\n</section>', 'admin reports panel')
write('templates/admin_dashboard.html', text)

# static/js/site.js
text = read('static/js/site.js')
text = replace_once(text, '    var navItems = Array.prototype.slice.call(header.querySelectorAll(".site-nav a, .nav-actions > *"));\n', '    var navItems = Array.prototype.slice.call(header.querySelectorAll(".site-nav a, .nav-actions > *"));\n    var isLocked = header.getAttribute("data-navbar-locked") === "true";\n', 'js lock var')
text = replace_once(text, '    function applyNavbarState(shouldCollapse) {\n        if (shouldCollapse === isCollapsed) {\n', '    function applyNavbarState(shouldCollapse) {\n        if (isLocked && !shouldCollapse) {\n            return;\n        }\n        if (shouldCollapse === isCollapsed) {\n', 'js apply state')
text = replace_once(text, '    function processScroll() {\n        var currentScrollY = lastKnownScrollY;\n', '    function processScroll() {\n        if (isLocked) {\n            applyNavbarState(true);\n            lastRunAt = performance.now();\n            ticking = false;\n            return;\n        }\n\n        var currentScrollY = lastKnownScrollY;\n', 'js process scroll')
text = text.replace('            if (isCollapsed) {', '            if (isCollapsed && !isLocked) {', 1)
text = text.replace('            if (isCollapsed) {', '            if (isCollapsed && !isLocked) {', 1)
text = text.replace('            if (isCollapsed && (event.key === "Enter" || event.key === " ")) {', '            if (isCollapsed && !isLocked && (event.key === "Enter" || event.key === " ")) {', 1)
write('static/js/site.js', text)

# static/css/site.css
text = read('static/css/site.css')
text = replace_once(text, '.site-header.navbar-collapsed .nav-group {\n    opacity: 0;\n    transform: translate3d(-0.7rem, 0, 0);\n    max-width: 0;\n    pointer-events: none;\n}\n', '.site-header.navbar-collapsed .nav-group {\n    opacity: 0;\n    transform: translate3d(-0.7rem, 0, 0);\n    max-width: 0;\n    pointer-events: none;\n}\n\n.site-header.navbar-locked .brand {\n    cursor: default;\n}\n', 'css locked brand')
text = replace_once(text, '.button-small {\n    padding: 0.72rem 1.1rem;\n    font-size: 0.95rem;\n}\n', '.button-small {\n    padding: 0.72rem 1.1rem;\n    font-size: 0.95rem;\n}\n\n.button-small + .button-small,\n.button-small + button.button-small {\n    margin-left: 0.4rem;\n}\n', 'css button small spacing')
text = replace_once(text, '.question-image {\n    border-radius: var(--radius-md);\n    border: 1px solid rgba(148, 163, 184, 0.24);\n    background: #ffffff;\n    box-shadow: var(--shadow-soft);\n    margin-top: 1rem;\n}\n', '.question-image {\n    border-radius: var(--radius-md);\n    border: 1px solid rgba(148, 163, 184, 0.24);\n    background: #ffffff;\n    box-shadow: var(--shadow-soft);\n    margin-top: 1rem;\n}\n\n.admin-question-image-preview {\n    max-width: 220px;\n}\n\n.report-question-box {\n    margin-top: 1rem;\n    padding-top: 0.25rem;\n}\n\n.report-question-box summary {\n    cursor: pointer;\n    color: var(--accent-dark);\n    font-weight: 600;\n}\n\n.report-question-box form {\n    margin-top: 0.85rem;\n}\n', 'css report styles')
write('static/css/site.css', text)

print('ok')
